### ISSUE TITLE
Homey Firmware Versie: 1.0.1 gives invalid_driver adding new devices

### ISSUE THREAD

**Issue by jeroenvano** [Thorarin/com.sensative#1] opened 2016-11-21 10:50 UTC
Homey Firmware Version: 1.0.1 gives "invalid_driver" adding new devices
Unable to add new devices

**Comment by ghost** [comment] 2016-11-22 22:28
Confirmed

**Comment by Thorarin** [comment] 2016-11-28 19:25
Turns out this is caused by an issue in the Homey firmware, which should be fixed in 1.0.3: https://github.com/athombv/homey/issues/1117

If you cannot wait for it to be released and you're familiar with Git, you can install the version from this branch: https://github.com/Thorarin/com.sensative/tree/driver-rename, but the downside is that you'll have to re-add your Strips and fix all your workflows to go back to the official app.

**Comment by Thorarin** [comment] 2016-12-06 21:11
Version 1.0.3 of the app has been submitted for approval to Athom.

**Closed as completed by Thorarin** 2016-12-06 21:11 UTC
